### ISSUE TITLE
Get Pikelet to build on wasm

### ISSUE THREAD

**Issue by brendanzab** [pikelet-lang/pikelet#138]
@sordina was [trying to get Pikelet to build on wasm](https://github.com/sordina/pigraph), but was running into issues with some system dependencies:

```
error[E0432]: unresolved import `sys`
 --> /Users/../.cargo/registry/src/github.com-1ecc6299db9ec823/mortal-0.1.5/src/screen.rs:9:5
  |
9 | use sys;
  |     ^^^ no `sys` in the root

error[E0432]: unresolved import `sys`
  --> /Users/../.cargo/registry/src/github.com-1ecc6299db9ec823/mortal-0.1.5/src/terminal.rs:10:5
   |
10 | use sys;
   |     ^^^ no `sys` in the root

error: aborting due to 2 previous errors
```

Getting Pikelet to build on wasm would be great, because it would let us build a 'try' website in the browser without needing to run it on a server, and also support use cases like the one above.

**Comment by brendanzab** [comment]
So I'm unsure if there are any resources out there for converting Rust libraries to work with WASM - not sure if you need to go all the way with not using `std` or not. I _do_ know that codespan accesses the file system here, which could be problematic: https://github.com/brendanzab/codespan/blob/85060bcf5d9a65878c2690e190a20d2c7fa7adf6/codespan/src/filemap.rs#L132-L145

**Comment by brendanzab** [comment]
Other places that might need some work is the cli directory, which thankfully is already under a cargo feature: https://github.com/pikelet-lang/pikelet/tree/master/src/cli

**Comment by boomshroom** [comment]
It comes to the fact that emscripten provides a unix like interface for wasm. Rust's built in WASM generator doesn't use the emscripten backend, and so all system calls must be provided manually.

If you write a javascript file that provides implementations of functions that get input and print characters, then it would be possible to use `wasm32-unknown-unknown`. On the other hand, emscripten provides standard `open`, `read`, and `write` syscalls, but from what I remember, those interact with the browser's developer console rather than the webpage. I could be wrong though.

**Comment by brendanzab** [comment]
So perhaps this should be a thing about adding no_std support? I wonder how we would handle all the dynamic allocation we do... 🤔

**Comment by brendanzab** [comment]
Iiinteresting: https://www.polaris64.net/resources/programming/p64lang_wasm/

**Comment by brendanzab** [comment]
Could be worth learning from their repo: https://github.com/polaris64/p64lang_rust

**Comment by Marwes** [comment]
> According to @boomshroom on Gitter, wasm32-unknown-unknown needs to be no_std, where as he thinks wasm32-unknown-emscripten is allowed to use std.

I am not sure this is true, I never needed to go `#![no_std]` for gluon but perhaps that has changed? The only real hurdles I had was to disable `rand` and `tokio` after that it all compiled.

**Comment by brendanzab** [comment]
Wait, I just tried locally, and this works:

```sh
rustup target add wasm32-unknown-unknown
cargo check --target wasm32-unknown-unknown --no-default-features
```

We should probably keep this tested on CI though.

@sordina: you can do this when including Pikelet as a dependency by doing the following:

```toml
[dependencies]
pikelet = { git = "https://github.com/pikelet-lang/pikelet", default-features = false }
```

This disables the 'cli' feature that is enabled by default. Note that you might still want to clone pikelet locally, and do a [temporary override](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#testing-a-bugfix) as you develop on it. You can do this by adding this to your `Cargo.toml` as well:

```toml
[patch.crates-io]
pikelet = { path = "../path/to/local/pikelet" }
```

**Comment by sordina** [comment]
Tried it and it compiles :)

**Comment by brendanzab** [comment]
Yeah, I think so! @boomshroom has made an attempt for the REPL at least, in #136, but I'd really like a better way to add imports. See #15.

**Comment by brendanzab** [comment]
I'm going to close this for now. The prelude is available, but the driver API is still kinda clunky to use. I've made an issue at #175 that begins trying to spec out some requirements to improve this.
