### ISSUE TITLE
Terminology bikeshed: Universe shifting/lifting/embiggening

### ISSUE THREAD

**Issue by brendanzab** [pikelet-lang/pikelet#140]
So I now have some sort of [McBride-style universe shifting](https://pigworker.wordpress.com/2015/01/09/universe-hierarchies/) implemented [in Pikelet](https://pikelet-lang.github.io/pikelet/language/universes.html#shifting-universes) in (excuse my poor technical writing). I was wondering about terminology here. Should we call the `foo^n` a:

- 'shift'
    - seems to be what RedTT is using
    - used a few times in McBride's blog post
- 'lift'
    - used in the [Agda stdlib](https://github.com/agda/agda-stdlib/blob/ae60e42c5806c0f8ed3226c98ed22af143b5b92c/src/Level.agda#L17-L19)
    - used in this report [Dependently typed lambda calculus with a lifting operator](https://www-sop.inria.fr/members/Damien.Rouhling/data/internships/M1Report.pdf)
    - does this fit with the [mathematical term](https://en.wikipedia.org/wiki/Lift_(mathematics))?

Wondering if you have any strong thoughts @jonsterling, @pigworker?

Prior discussion and implementation here: #10, #125

cc. @LightAndLight

**Comment by brendanzab** [comment]
- inflate
- grow
- elevate

**Comment by jonsterling** [comment]
@brendanzab I favor Hoist, but I don't know :laughing:

**Comment by brendanzab** [comment]
Ah yes, I forgot that one from McBride's post. This was my silly imagining of hoisting an identity function in Pikelet:

![universe hoisting](https://user-images.githubusercontent.com/695077/45629781-81e97e00-bada-11e8-97c6-3caaa454414a.jpg)

**Comment by brendanzab** [comment]
Only issue is that it might confuse JavaScript programmers!

**Comment by brendanzab** [comment]
[This draft paper](https://www.irif.fr/~sozeau/research/publications/drafts/Cumulative_Inductive_Types_in_Coq.pdf) seems to refer to McBride's thing as shifting:

> In [15], McBride presents a proposal for internalizing “shifting” of universe polymorphic constructions to higher universe levels akin to an explicit version of cumulativity

Gonna just go with 'shifting' for now. If you disagree, please pipe up here! 😄
