### ISSUE TITLE
Workspace doesn't build on a headless linux system

### ISSUE THREAD

**Issue by brson** [pikelet-lang/pikelet#242]
The error:

```
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config
\" \"--libs\" \"--cflags\" \"x11\" \"x11 >= 1.4.99.1\"", output: Output { status: ExitStatus(ExitStatus(25
6)), stdout: "", stderr: "Package x11 was not found in the pkg-config search path.\nPerhaps you should add
 the directory containing `x11.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'x11\' found
\nPackage x11 was not found in the pkg-config search path.\nPerhaps you should add the directory containin
g `x11.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'x11\' found\n" } }', /home/ubuntu/.
cargo/registry/src/github.com-1ecc6299db9ec823/x11-2.18.2/build.rs:36:67
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

This is because pikelet-editor needs x11. By default, pikelet-cli needs pikelet-editor, so figuring out how to invoke cargo to run the repl without building the gui components was not trivial. This is what I ended up running:

```
cargo run --manifest-path=pikelet-cli/Cargo.toml --no-default-features -- repl
```

A good fix for this isn't obvious. The easy one is to make the gui optional so that the cli builds on more systems. A harder one would be to add build scripts to figure out if x is available and stub the editor out into a nop if not.

**Comment by brendanzab** [comment]
Ah dang! Yeah it uses iced, which I might move away from in the future. I'm trying to decide on an approach for playing around with user interfaces for editing types (see the [`pikelet-edittor`'s README](https://github.com/pikelet-lang/pikelet/tree/main/pikelet-editor#readme)). Like, it might be easier to do something more browser based in the short term, with an eye to have alternate, native front-ends later on. 

Maybe I should just remove the stub iced window for now - it's annoying to have to build the iced dependencies all the time, if I'm honest, especially seeing as they aren't providing much value yet!

Thanks for the bug report at any rate!
