### ISSUE TITLE
Let and where bindings

### ISSUE THREAD

**Issue by brendanzab** [pikelet-lang/pikelet#26]
I've implemented concrete syntax for `let` and `where` bindings, but not hooked them up to the core syntax yet. We need to do this at some stage!

I've been thinking - could we perhaps desugar them into dependent records like [1ML](https://people.mpi-sws.org/~rossberg/1ml/) does? Eg:

- `let x = y; .. in z` to `(record { x = y, .., body = z }).body`
- `z where x = y; ..` to `(record { x = y, .., body = z }).body`

Not sure what the implications for alpha equality would be though. Also whether this is compatible with how we want bindings to be evaluated. 🤔

**Comment by brendanzab** [comment]
As I discussed today with @markbrown, one complication with this sugaring is whether we want to support shadowing in let and where bindings. We might want to prevent this in records, but allow it in where bindings - I dunno.

**Comment by aepsil0n** [comment]
Just to throw in another idea: I've never really grown to like the syntax of `let` and `where` too much… so this is inspired from more imperative languages:

```
record { x = y, .., z }
record { z, x = y, .. }
```

i.e. turn the record syntax into a more general block construct that has effectively the same semantics as let or where. In practice, this may look a lot like blocks in Rust do, but without any implied execution order, of course. This may also be nice for defining modules as expressions like [Gluon does](http://gluon-lang.org/book/modules.html).

**Comment by brendanzab** [comment]
Yes, [1ML](https://people.mpi-sws.org/~rossberg/1ml/) actually desugars let bindings into records.

I was indeed hoping to allow you to [define modules using records](https://github.com/pikelet-lang/pikelet/issues/2)! The one thing that has been holding me back from doing this at the top-level, at least for now, has been trying to think about how this interacts with module-level effects. For example if we wanted to add generative modules (ie. that are distinguished by name, rather than by structure), or wanted to have some way of defining new inductive data types.
