### ISSUE TITLE
Use "goldenfiles" for some tests

### ISSUE THREAD

**Issue by brendanzab** [pikelet-lang/pikelet#78]
At the moment I'm explicitly writing out asts manually in some of my tests. This is tedious to update when I change the AST, and it would be handy to just get a diff of the changes automatically generated instead. This would allow us to be more liberal with our testing too. 'Goldenfiles' (also known as 'snapshot testing') seems like a good answer to this. There is a [crate called `goldenfile`](https://crates.io/crates/goldenfile) that does this for Rust.

Here are some tests that I think could be improved with this method:

- https://github.com/brendanzab/pikelet/blob/53a0261d0026f0d3b60083b2740d24ae86891f04/src/syntax/translation/desugar/test.rs#L43-L292
- https://github.com/brendanzab/pikelet/blob/53a0261d0026f0d3b60083b2740d24ae86891f04/src/semantics/tests/normalize.rs#L5-L121

We could probably add some more tests after that once we set up a nice, repeatable process for this.

**Comment by brendanzab** [comment]
Would you be interested in picking this up @adrianwong?

**Comment by adrianwong** [comment]
Sure, I'll give it a shot @brendanzab!

**Comment by brendanzab** [comment]
Seems that this repo does all the golden tests in one test: https://github.com/slava-sh/rust-bundler/blob/master/tests/golden.rs

It would be interesting to see what the test failures looked like!

**Comment by adrianwong** [comment]
I've hit a bit of a snag with the snapshot testing of the `arrow`, `lam_ann`, and `pi` tests in the `desugar` module. All three consistently fail snapshot testing due to the generation of a unique `GenId(u32)` struct on each run.

From what I am able to tell, the presence of the `GenId` node in the AST corresponds with `nameless::bind( Name::user("_") )`, but the rest is a bit beyond me.

Thoughts? What I've done so far can be found [here](https://github.com/adrianwong/pikelet/tree/goldenfiles-tests).

**Comment by brendanzab** [comment]
Oh damn! That's because there is a global name generator that makes a special name that is unique for the entire program. The global state is in the `nameless` crate, which makes it quite hard to find! https://github.com/brendanzab/nameless/blob/e7832261f7898faebe6f5571d7aa30950c1ecfa8/nameless/src/name.rs#L30-L42

I didn't want to use dependency injection for it, but perhaps I might need to.

Perhaps we could just leave those tests for now?

**Comment by brendanzab** [comment]
Super neat thing is that it's chowing that arrow types, eg. `Int -> Int` are actually just special cases of dependent functions/pi types/foralls: `(x : Int) -> Int`, where the parameter is not mentioned in the return type.

**Comment by adrianwong** [comment]
Ah, whoops, I had it backwards. So in the tests when we parse, e.g. `r"(x : Type -> Type) -> x"`, we then assert that the first `Type` has `name` `x`, whereas the second type doesn't have one, hence the `Name::user("_")`.

**Comment by adrianwong** [comment]
Ok I'll leave the snapshot testing out for those three tests then!

**Comment by brendanzab** [comment]
yup, spot on!
